/** @type {import('next').NextConfig} */
const nextConfig = {
  devIndicators: false,
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: "https",
        hostname: "d3qnldyv492i08.cloudfront.net",
      },
      {
        protocol: "https",
        hostname: "api.qrserver.com",
      },
    ],
  },
  env: {
    WEBSITE_URL:
      process.env.NODE_ENV === "production"
        ? "https://ashapurna.com/"
        : "http://localhost:3000/",
    // WEBSITE_URL: "https://ashapurna.com/",
    // WEBSITE_URL: 'https://www.ashapurna.com/',
    // BASE_API_URL: 'http://ashapurna.digitaltyari.com/api/Web/',
    // BASE_API_URL: 'https://api.ashapurna.com/api/web/',
    BASE_API_URL: "https://apiservices.ashapurna.com/api/web/",
    ENQUIRY_FORM: "enquiries",
    CONTACT_US_FORM: "enquiries/contact",
    PARTNER_SUBJECTS: "enquiries/subjects",
    INVESTOR_SUBJECTS: "enquiries/property-types",
    ENQUIRY_SUBJECTS: "home/properties",
    REFERRAL_FORM: "enquiries/referral-schema",
    REFERRAL_LOCATIONS: "enquiries/locations",
    CAREER_DATA: "career",
    CAREER_FORM: "career/enquiry",
    CAREER_FORM_RESUME: "https://admin.ashapurna.com/api/upload-career-resume",
    PROJECT_VIDEO_PATH:
      "https://d3qnldyv492i08.cloudfront.net/ashapurna/images/projects/full_video_path/",
    SEO_CONTENT_API: "seo-content",
    EXTRA_LINKS: "footer-extra-links",
    HOME_API: "home",
    ABOUTUS_API: "about-us",
    CORPORATE_API: "about-us/corporate-profile",
    PROJECT_CATEGORY_API: "project/categories",
    PROJECT_LISTING_API: "project/listing",
    PROJECT_DETAILS_API: "project/details",
    PROJECT_FLOORS_API: "project/floor-plans",
    PROJECT_360_API: "project/360-views",
    PROJECT_CONSTRUCTIONS_API: "project/constructions",
    PROJECT_GALLERY_API: "project/gallery",
    RENTAL_LEASE_API: "project/lease-rental",
    COMMON_API: "common-content",
    JOURNEY_API: "about-us/our-journies",
    MANAGEMENT_API: "about-us/management-speak",
    TEAM_API: "about-us/our-team",
    MEDIA_EVENT_API: "media-events",
    MEDIA_EVENT_DETAIL_API: "media-events/details",
    NRICORNER_API: "about-us/nri-corner",
    INVESTORS_CLUB: "investor-club",
    NEWSLETTER_API: "newsletter",
    SEND_OTP: "send-otp",
    VERIFY_OTP: "verify-otp",
    WHYINVEST_API: "about-us/why-invest-in-jodhpur",
    CSR_API: "about-us/csr-social-resposibilities",
    TESTIMONIALS_API: "testimonials",
    EMICALCULATOR_API: "emi-calculator",
    BECOMEPARTNER_API: "become-partner",
    RERA_API: "rera-disclaimer",
    REFERRAL_API: "referal-schema",
    PRIVACY_POLICY_API: "privacy-policy",
    TERMS_CONDITIONS_API: "terms-condition",
    SITEMAP_DATA: "site-map",
    PROJECT_DETAILS_V2_API: "project/details/v2",
    PROJECT_AMENTITY_API: "project/amentity",
    PROJECT_LOCATIONS_API: "project/locations",
    PROJECT_VIDEO_GALLERY_API: "project/video-gallery",
  },
};

export default nextConfig;
