const ourJourneyProjects = [
  {
    id: 1,
    title: "Ashapurna Township Uchiyarda",
    year: 1997,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 2,
    title: "Ashapurna Township Jalore",
    year: 1999,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 3,
    title: "Ashapurna Township Sanchore",
    year: 2001,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 4,
    title: "Ashapurna Nagar",
    year: 2004,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 5,
    title: "Ashapurna City",
    year: 2005,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 6,
    title: "Ashapurna Township Pali",
    year: 2006,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 7,
    title: "Ashapurna Valley",
    year: 2006,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 8,
    title: "Ashapurna Mall & Multiplex",
    year: 2007,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 9,
    title: "Ashapurna Township Sheoganj",
    year: 2007,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 10,
    title: "Ashapurna Commercial",
    year: 2008,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 11,
    title: "Ashapurna Tower",
    year: 2008,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 12,
    title: "Ashapurna Mohan Villas",
    year: 2009,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 13,
    title: "Ashapurna Maa Bhagwati Nagar",
    year: 2009,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 14,
    title: "Ashapurna Greens",
    year: 2010,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 15,
    title: "Ashapurna Enclave",
    year: 2010,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 16,
    title: "Ashapurna NanoMax",
    year: 2011,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 17,
    title: "Ashapurna Empire",
    year: 2012,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 18,
    title: "Ashapurna Paradise",
    year: 2012,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 19,
    title: "Ashapurna Chandan Vihar",
    year: 2013,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 20,
    title: "Ashapurna Nano Grand",
    year: 2013,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 21,
    title: "Ashapurna Platinum",
    year: 2013,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 22,
    title: "Ashapurna Hotel Jaipur",
    year: 2013,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 23,
    title: "Ashapurna Crown Plaza",
    year: 2014,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 24,
    title: "Ashapurna Golden Valley",
    year: 2014,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 25,
    title: "Ashapurna Buddha Group Of Institutions, Udaipur",
    year: 2014,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 26,
    title: "Ashapurna Heritage",
    year: 2015,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 27,
    title: "Ashapurna Nano Avenue",
    year: 2015,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 28,
    title: "Ashapurna Wind Mill & Solar Plant",
    year: 2015,
    projectType: "Residential",
    area: 32,
  },
   {
    id: 29,
    title: "Ashapurna Nano Regiment",
    year: 2016,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 30,
    title: "Ashapurna Basera",
    year: 2017,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 31,
    title: "Ashapurna Nano Plaza",
    year: 2019,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 32,
    title: "Ashapurna Aangan",
    year: 2020,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 33,
    title: "Ashapurna Anmol",
    year: 2020,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 34,
    title: "Ashapurna Aangan Prime",
    year: 2021,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 35,
    title: "Ashapurna NRI",
    year: 2021,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 36,
    title: "Ashapurna Pachpapda",
    year: 2022,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 37,
    title: "Ashapurna MohanBagh",
    year: 2023,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 38,
    title: "Ashapurna Valley Orchard",
    year: 2024,
    projectType: "Residential",
    area: 32,
  },
  {
    id: 39,
    title: "Ashapurna NRI Vistara",
    year: 2025,
    projectType: "Residential",
    area: 32,
  },
];

export default ourJourneyProjects;
